---
title: "Exercise Ch4"
author: "Vincent"
date: "2021/11/27"
output: html_document
---
```{r}
participations <- 
list('session 3',c("session 1", "session 2", "session 3"),'session 3',c("session 2", "session 1"),c("session 3", "session 1"),c("session 3", "session 2", "session 1"),'session 2','session 1',c("session 2", "session 1", "session 3"),c("session 3", "session 1", "session 2"))
```

```{r}
# sessions that 1st student attended
participations[[1]] 
# sessions that 2nd student attended
participations[[2]]
```

```{r}
table(unlist(participations))
```


```{r}
fct <- factor(
  c('參','貮','貮','貮','壹','貮','參','貮','參','參'),
  levels=c('壹','貮','參')
  )
fct_num<-as.numeric(fct)
fct_num
```

```{r}
fct = 
factor(
  c('۶','۹','۸','۹','۶','۸','۸','۵','۹','۹'),
  levels = c("۵", "۶", "۷", "۸", "۹")
  )
fct_num2 = as.numeric(fct)
fct_num2
```
```{r}

studentLetterGrades <- {
  # Task map c("C", "B-", "B", "B+", "A-", "A", "A+") to c(2, 2.5, 3, 3.5, 4, 4.5, 5)
    letter_grades <- c("C", "B-", "B", "B+", "A-", "A", "A+")
    numeric_grades <- c(2, 2.5, 3, 3.5, 4, 4.5, 5)
    studentGrades <- c('B','A','A+','B+','A-','B','B-','B','A+','B+','C','B-','B-','B','C','C','B+','B','B+','B')
  # step1: for each grade in studentGrades find its position in c("C", "B-", "B", "B+", "A-", "A", "A+") so if studentGrades = c("C","A-"), step1 = c(1, 5) since c("C", "B-", "B", "B+", "A-", "A", "A+")[c(1, 5)] will give him "C", "A-"
  step1 <- as.numeric(
    factor(
      studentGrades ,
      levels = letter_grades
    )
    )
  # step2: Use step1 result as position indices to retrieve from c(2, 2.5, 3, 3.5, 4, 4.5, 5). From previous example, step1=c(1, 5), then  c(2, 2.5, 3, 3.5, 4, 4.5, 5)[step1] will give him c(2, 4)
  step2 =
      factor(
      step1 * 0.5 + 1.5 ,
      levels = numeric_grades
    )
}
```






